"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import {
    FileText,
    Calendar,
    CheckCircle2,
    Printer,
    Share2,
    ArrowRight,
    AlertTriangle
} from "lucide-react";
import Sidebar from "@/components/Sidebar";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

interface ReportSection {
    title: string;
    content: string;
    chart_type?: string;
    chart_data?: Record<string, unknown>;
}

interface ReportData {
    session_id: string;
    title: string;
    generated_at: string;
    sections: ReportSection[];
}

export default function ReportPage() {
    const router = useRouter();
    const [loading, setLoading] = useState(true);
    const [data, setData] = useState<ReportData | null>(null);
    const [error, setError] = useState<string | null>(null);
    const [exporting, setExporting] = useState(false);

    useEffect(() => {
        const stored = localStorage.getItem("analysis_session");
        if (!stored) { router.push("/upload"); return; }
        const session = JSON.parse(stored);
        fetchReport(session.session_id);
    }, [router]);

    const fetchReport = async (sessionId: string) => {
        try {
            const response = await fetch(`${API_BASE}/report/${sessionId}`);
            if (!response.ok) throw new Error("Couldn't load the report. Please try again.");
            const result = await response.json();
            setData(result);
        } catch (err) {
            setError(err instanceof Error ? err.message : "Couldn't load the report. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const exportAsPDF = () => {
        setExporting(true);
        const printContent = `
            <html>
                <head>
                    <title>${data?.title || "Report"}</title>
                    <style>
                        body { font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; padding: 60px; max-width: 900px; margin: 0 auto; color: #0f172a; line-height: 1.65; }
                        h1 { font-size: 28px; font-weight: 600; color: #0f172a; margin: 0 0 8px; letter-spacing: -0.01em; }
                        .date { color: #64748b; font-size: 13px; margin-bottom: 40px; }
                        h2 { font-size: 16px; font-weight: 600; color: #0f172a; margin-top: 36px; margin-bottom: 12px; }
                        p { font-size: 15px; margin-bottom: 20px; color: #334155; }
                        .section { margin-bottom: 32px; padding-bottom: 24px; border-bottom: 1px solid #e2e8f0; }
                        .section:last-child { border-bottom: none; }
                        .section p { white-space: pre-wrap; }
                    </style>
                </head>
                <body>
                    <h1>${data?.title || "Report"}</h1>
                    <p class="date">Generated by InsightStream • ${data ? new Date(data.generated_at).toLocaleDateString() : ""}</p>
                    ${data?.sections.map(s => `
                        <div class="section">
                            <h2>${s.title}</h2>
                            <p>${s.content}</p>
                        </div>
                    `).join("")}
                </body>
            </html>
        `;

        try {
            const printWindow = window.open("", "_blank");
            if (printWindow) {
                printWindow.document.write(printContent);
                printWindow.document.close();
                printWindow.print();
            }
        } finally {
            setExporting(false);
        }
    };

    if (loading) {
        return (
            <div className="min-h-screen bg-slate-50 flex">
                <Sidebar />
                <div className="flex-1 flex flex-col items-center justify-center">
                    <div className="relative">
                        <div className="w-12 h-12 border-2 border-slate-200 border-t-indigo-600 rounded-full animate-spin" />
                        <FileText className="w-4 h-4 text-indigo-600 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
                    </div>
                    <p className="mt-5 text-sm text-slate-500">Preparing your report…</p>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 flex">
            <Sidebar />

            <main className="flex-1 px-8 py-10">
                <div className="max-w-3xl mx-auto">
                    {error && (
                        <div className="mb-8 p-4 rounded-lg bg-rose-50 border border-rose-200 text-rose-700 text-sm flex items-start gap-3">
                            <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" />
                            <span>{error}</span>
                        </div>
                    )}

                    {data && (
                        <>
                            {/* Report header */}
                            <header className="mb-10 pb-8 border-b border-slate-200">
                                <p className="text-xs font-medium text-indigo-700 uppercase tracking-wide mb-3">
                                    Report
                                </p>
                                <h1 className="text-3xl md:text-4xl font-semibold text-slate-900 tracking-tight mb-4">
                                    {data.title}
                                </h1>
                                <div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-slate-500">
                                    <div className="flex items-center gap-1.5">
                                        <Calendar className="w-4 h-4" />
                                        <span>
                                            {new Date(data.generated_at).toLocaleDateString(undefined, { dateStyle: "long" })}
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-1.5">
                                        <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                                        <span>Reviewed by InsightStream</span>
                                    </div>
                                </div>
                            </header>

                            {/* Report sections */}
                            <article className="space-y-10">
                                {data.sections.map((section, i) => (
                                    <section key={i}>
                                        <div className="flex items-baseline gap-3 mb-3">
                                            <span className="text-xs font-medium text-slate-400 tabular-nums">
                                                {String(i + 1).padStart(2, "0")}
                                            </span>
                                            <h2 className="text-lg font-semibold text-slate-900">
                                                {section.title}
                                            </h2>
                                        </div>
                                        <div className="text-base text-slate-700 leading-relaxed whitespace-pre-wrap pl-9">
                                            {section.content}
                                        </div>
                                    </section>
                                ))}
                            </article>

                            {/* Export panel */}
                            <div className="mt-16 p-6 rounded-lg bg-white border border-slate-200">
                                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-5">
                                    <div>
                                        <h3 className="text-base font-semibold text-slate-900 mb-1">
                                            Save or share this report
                                        </h3>
                                        <p className="text-sm text-slate-500">
                                            Print to PDF or send a copy to your team.
                                        </p>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <button
                                            onClick={exportAsPDF}
                                            disabled={exporting}
                                            className="flex items-center gap-2 px-5 py-2.5 rounded-md bg-indigo-600 hover:bg-indigo-700 disabled:opacity-60 disabled:cursor-not-allowed text-white text-sm font-medium transition-colors"
                                        >
                                            <Printer className="w-4 h-4" />
                                            {exporting ? "Preparing…" : "Print to PDF"}
                                        </button>
                                        <button
                                            onClick={() => window.print()}
                                            className="flex items-center justify-center w-10 h-10 rounded-md bg-white hover:bg-slate-50 border border-slate-200 text-slate-600 transition-colors"
                                            aria-label="Share"
                                            title="Share"
                                        >
                                            <Share2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                </div>
                            </div>

                            {/* Done state */}
                            <div className="mt-6 p-6 rounded-lg bg-emerald-50 border border-emerald-200 text-center">
                                <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white border border-emerald-200 mb-4">
                                    <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                                </div>
                                <h2 className="text-lg font-semibold text-slate-900 mb-1.5">
                                    You&apos;re all done
                                </h2>
                                <p className="text-sm text-slate-600 mb-5 max-w-md mx-auto">
                                    Want to analyze another file? Start a new session below.
                                </p>
                                <button
                                    onClick={() => router.push("/upload")}
                                    className="inline-flex items-center gap-2 px-5 py-2.5 rounded-md bg-slate-900 hover:bg-slate-800 text-white text-sm font-medium transition-colors"
                                >
                                    Upload a new file
                                    <ArrowRight className="w-4 h-4" />
                                </button>
                            </div>
                        </>
                    )}
                </div>
            </main>
        </div>
    );
}