"""
engine/findings/types.py
─────────────────────────
Core Finding dataclass with confidence and impact tiers.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


@dataclass
class Finding:
    title: str
    body: str
    confidence: Literal["HIGH", "MEDIUM", "LOW"]
    impact: Literal["CRITICAL", "IMPORTANT", "MINOR"]
    evidence: dict = field(default_factory=dict)

    # Optional narrative header (generated by Task 7)
    narrative_title: str = ""
